### ISSUE TITLE
Isn't this piracy?

### ISSUE THREAD

**Issue by joelewing** [felixrieseberg/macintosh.js#7]
I am not a lawyer, but I understand that you are distributing copies of licensed software.

A very cool project though!

**Comment by Seshpenguin** [comment]
Things like this are usually considered historical preservation... I'm not sure of the specific legalities (whether it's proper legal or just companies turning a blind-eye), but in practice it *should* be fine (Websites like Macintosh Garden/Repository, Archive.org, etc, host hundreds of gigabytes of old Macintosh software).

**Comment by joelewing** [comment]
Although I do not think there is any risk of prosecution, I'm not aware of stipulations that waive copyright claims for the purposes of historical preservation.

**Comment by lachesis** [comment]
I am also not a lawyer, but I think there's some merits to a fair use claim for preservation. Here's a specific opinion from the US Gov regarding exemption from DMCA laws prohibiting circumvention of DRM:
"3. Computer programs and video games distributed in formats that have become obsolete and which require the original media or hardware as a condition of access. ...The register has concluded that to the extent that libraries and archives wish to make preservation copies of published software and videogames that were distributed in formats that are (either because the physical medium on which they were distributed is no longer in use or because the use of an obsolete operating system is required), such activity is a noninfringing use covered by section 108(c) of the Copyright Act."
https://www.copyright.gov/1201/docs/fedreg-notice-final.pdf
https://en.wikipedia.org/wiki/Abandonware#DMCA

**Comment by felixrieseberg** [comment]
I'm also not a lawyer, so I can't answer this question, I'm afraid.
